apiVersion: apps/v1 
kind: Deployment
metadata:
  name: springapp 
spec:
  selector:
    matchLabels:
      app: springapp
  replicas: 3 
  template: 
    metadata: 
      name: springapp
      labels:
        app: springapp
    spec:
      containers: 
        - name: springapp
          image: bricelab21/spring-boot-mongo 
          ports: 
          - containerPort: 8080
          env:
          - name: MONGO_DB_USERNAME
            value: devdb
          - name: MONGO_DB_PASSWORD
            value: devdb@123
          - name: MONGO_DB_HOSTNAME 
            value: mongodb 
---
---
apiVersion: v1
kind: Service
metadata:
  name: springapp
spec:
  type: NodePort
  selector:
    app: springapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32010
