- hosts: all
  roles: 
  - java 
  - common


# playbook 2

- hosts: k8s
  become: true
  tasks:
  - name: create a file
    shell: touch /tmp/app.yml
  - name: copy file
    copy: src=/home/ansible/myapp.yml dest=/tmp/
  - name: install packages
    yum: name=[git, tree, wget] state=present
    when: "os_family==redhat"
